"use client";

import { Bot, Plus } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ApiNotice, Button, Drawer, EmptyState, Field, PageHeader, StatCard, StatusBadge } from "../../../components/ui";
import { controlApi, ControlApiError, type Membership, type Tenant } from "../../../lib/control-api";

export default function TenantDetailPage(){const params=useParams<{tenantId:string}>();const tenantId=params.tenantId;const[tenant,setTenant]=useState<Tenant|null>(null);const[members,setMembers]=useState<Membership[]>([]);const[error,setError]=useState<unknown>();const[drawer,setDrawer]=useState(false);const load=useCallback(()=>Promise.all([controlApi.getTenant(tenantId),controlApi.listMembers(tenantId)]).then(([t,m])=>{setTenant(t);setMembers(m.members)}).catch(setError),[tenantId]);useEffect(()=>{void load()},[load]);async function remove(userId:string){if(!confirm("确认移除该租户成员？"))return;try{await controlApi.removeMember(tenantId,userId);await load()}catch(caught){setError(caught instanceof ControlApiError&&caught.code==="OWNER_REQUIRES_TRANSFER"?new Error("Owner 不能直接移除，请先完成所有权转移"):caught)}}if(!tenant)return <main><div className="loading-mark"/></main>;const owner=tenant.role==="OWNER";return <><PageHeader eyebrow="TENANT MEMBERSHIP" title={tenant.name} description={`Tenant ${tenant.slug} · ${tenant.id}`} action={<div className="header-actions"><Link className="button secondary" href={`/tenants/${encodeURIComponent(tenantId)}/agents`}><Bot size={15}/>Agent 画布</Link>{owner&&<Button onClick={()=>setDrawer(true)}><Plus size={15}/>添加成员</Button>}</div>}/><ApiNotice error={error}/><div className="stats-grid"><StatCard detail="当前 Membership 数量" label="成员" value={members.length}/><StatCard detail="当前登录账号在此租户中的角色" label="我的角色" value={tenant.role??"MEMBER"}/><StatCard detail="租户服务状态" label="状态" value={tenant.status}/></div><div className="panel">{members.length===0?<EmptyState detail="当前租户没有可展示的成员。" title="没有成员"/>:<div className="table-wrap"><table><thead><tr><th>用户 ID</th><th>角色</th><th>创建者</th><th>加入时间</th><th>操作</th></tr></thead><tbody>{members.map((member)=><tr key={member.id}><td><strong>{member.user_id}</strong></td><td><StatusBadge tone={member.role==="OWNER"?"blue":"gray"}>{member.role}</StatusBadge></td><td>{member.created_by}</td><td>{new Date(member.created_at).toLocaleString("zh-CN")}</td><td>{owner?<Button disabled={member.role==="OWNER"} onClick={()=>void remove(member.user_id)} variant="danger">移除</Button>:"—"}</td></tr>)}</tbody></table></div>}</div>{drawer&&<AddMemberDrawer onClose={()=>setDrawer(false)} onDone={()=>{setDrawer(false);void load()}} tenantId={tenantId}/>}</>}
function AddMemberDrawer({tenantId,onClose,onDone}:{tenantId:string;onClose:()=>void;onDone:()=>void}){const[userId,setUserId]=useState("");const[error,setError]=useState<unknown>();async function submit(e:FormEvent){e.preventDefault();try{await controlApi.addMember(tenantId,userId);onDone()}catch(caught){setError(caught)}}return <Drawer description="目标用户必须是已激活的平台账号。" onClose={onClose} title="添加租户成员"><form className="form-stack" onSubmit={(e)=>void submit(e)}><ApiNotice error={error}/><Field label="用户 ID" onChange={(e)=>setUserId(e.target.value)} required value={userId}/><div className="form-actions"><Button onClick={onClose} type="button" variant="secondary">取消</Button><Button type="submit">添加</Button></div></form></Drawer>}
